language: node_js
node_js:
  - '8'
install: npm install
services:
  - postgresql
env:
  - NODE_ENV=test
before_script:
  - psql -c 'create database recipe_test;' -U postgres
  - psql -c "CREATE USER emasys WITH PASSWORD 'root';" -U postgres
  - 'sequelize db:migrate:undo:all'
  - 'sequelize db:migrate'
after_success:
  - npm run coverage
