language: node_js
node_js:
 - "8.3.0"
branches:
  only:
    - develop
services:
  - postgresql
before_script:
  - psql -c 'create database recipes-test;' -U postgres 
install:
  - npm install sequelize
  - npm install sequelize-cli
  - npm install pg
  - npm install pg-hstore
script:
  - sequelize db:migrate --env test

after_success: npm run coverage